function CpNaca0012Alfa5 = importfile1(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  CPNACA0012ALFA5 = IMPORTFILE1(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the numeric data.
%
%  CPNACA0012ALFA5 = IMPORTFILE1(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  CpNaca0012Alfa5 = importfile1("/home/luigi/Hess Smith method/Hess Smith classico/CpNaca0012Alfa5.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 19-Dec-2023 19:20:31

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["VarName1", "x", "Var3"];
opts.SelectedVariableNames = ["VarName1", "x"];
opts.VariableTypes = ["double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, "Var3", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var3", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "VarName1", "TrimNonNumeric", true);
opts = setvaropts(opts, "VarName1", "ThousandsSeparator", ",");

% Import the data
CpNaca0012Alfa5 = readtable(filename, opts);

%% Convert to output type
CpNaca0012Alfa5 = table2array(CpNaca0012Alfa5);
end